version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    command:
     - --api.insecure=true
     - --providers.docker
     - --providers.docker.useBindPortIP=true
     - --entrypoints.web.address=:80
     - --entrypoints.websecure.address=:443
     - --certificatesresolvers.leresolver.acme.httpchallenge=true
     - --certificatesresolvers.leresolver.acme.email=sebastian@michaelsen.io
     - --certificatesresolvers.leresolver.acme.storage=./acme.json
     - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Path(`/whoami`)"

  phpunit:
    image: nginx
    volumes:
      - /home/ci/phpunit:/usr/share/nginx/html
    labels:
      - "traefik.http.routers.phpunit.rule=PathPrefix(`/phpunit/`)"

  allure_typo3:
    image: frankescobar/allure-docker-service
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=1
    volumes:
      - /home/ci/allure_typo3/allure_results:/app/allure-results
      - /home/ci/allure_typo3/allure_reports:/app/default-reports
    labels:
      - "traefik.http.routers.allure_typo3.rule=PathPrefix(`/allure_typo3/`)"
      - "traefik.http.services.allure_typo3.loadbalancer.server.port=5050"
