logLevel = "INFO"
  defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[docker]
  watch = true

 # Force HTTPS
[entryPoints.web]
  address = ":80"
  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"
[entryPoints.websecure]
  address = ":443"

# Let's encrypt configuration
[acme]
  email="sebastian.michaelsen@swisscom.com"
  storage="/etc/traefik/acme/acme.json"
  entryPoint="https"
  acmeLogging=true
  OnHostRule=true
  [acme.httpChallenge]
    entryPoint = "http"
